name: CI Docker Lab

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Build principal
      run: docker build -t principal ./docker-nginx-wsl2/principal

    - name: Build portal
      run: docker build -t portal ./docker-nginx-wsl2/portal

    - name: Build erp
      run: docker build -t erp ./docker-nginx-wsl2/erp
